/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				ctp: {
					rosewater: '#f5e0dc',
					flamingo: '#f2cdcd',
					pink: '#f5c2e7',
					mauve: '#cba6f7',
					red: '#f38ba8',
					maroon: '#eba0ac',
					peach: '#fab387',
					yellow: '#f9e2af',
					green: '#a6e3a1',
					teal: '#94e2d5',
					sky: '#89dceb',
					sapphire: '#74c7ec',
					blue: '#89b4fa',
					lavender: '#b4befe',
					text: '#cdd6f4',
					subtext1: '#bac2de',
					subtext0: '#a6adc8',
					overlay2: '#9399b2',
					overlay1: '#7f849c',
					overlay0: '#6c7086',
					surface2: '#585b70',
					surface1: '#45475a',
					surface0: '#313244',
					base: '#1e1e2e',
					mantle: '#181825',
					crust: '#11111b',
				},
			},
			fontFamily: {
				mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'Courier', 'monospace'],
			},
			typography: ({ theme }) => ({
				ctp: {
					css: {
						'--tw-prose-body': theme('colors.ctp.text'),
						'--tw-prose-headings': theme('colors.ctp.mauve'),
						'--tw-prose-lead': theme('colors.ctp.subtext1'),
						'--tw-prose-links': theme('colors.ctp.blue'),
						'--tw-prose-bold': theme('colors.ctp.lavender'),
						'--tw-prose-counters': theme('colors.ctp.rosewater'),
						'--tw-prose-bullets': theme('colors.ctp.rosewater'),
						'--tw-prose-hr': theme('colors.ctp.surface0'),
						'--tw-prose-quotes': theme('colors.ctp.subtext1'),
						'--tw-prose-quote-borders': theme('colors.ctp.surface2'),
						'--tw-prose-captions': theme('colors.ctp.subtext0'),
						'--tw-prose-code': theme('colors.ctp.pink'),
						'--tw-prose-pre-code': theme('colors.ctp.text'),
						'--tw-prose-pre-bg': theme('colors.ctp.mantle'),
						'--tw-prose-th-borders': theme('colors.ctp.surface1'),
						'--tw-prose-td-borders': theme('colors.ctp.surface0'),
						'--tw-prose-invert-body': theme('colors.ctp.text'),
						'--tw-prose-invert-headings': theme('colors.ctp.mauve'),
						'--tw-prose-invert-lead': theme('colors.ctp.subtext1'),
						'--tw-prose-invert-links': theme('colors.ctp.blue'),
						'--tw-prose-invert-bold': theme('colors.ctp.lavender'),
						'--tw-prose-invert-counters': theme('colors.ctp.rosewater'),
						'--tw-prose-invert-bullets': theme('colors.ctp.rosewater'),
						'--tw-prose-invert-hr': theme('colors.ctp.surface0'),
						'--tw-prose-invert-quotes': theme('colors.ctp.subtext1'),
						'--tw-prose-invert-quote-borders': theme('colors.ctp.surface2'),
						'--tw-prose-invert-captions': theme('colors.ctp.subtext0'),
						'--tw-prose-invert-code': theme('colors.ctp.pink'),
						'--tw-prose-invert-pre-code': theme('colors.ctp.text'),
						'--tw-prose-invert-pre-bg': theme('colors.ctp.mantle'),
						'--tw-prose-invert-th-borders': theme('colors.ctp.surface1'),
						'--tw-prose-invert-td-borders': theme('colors.ctp.surface0'),
						code: {
							backgroundColor: theme('colors.ctp.surface0'),
							color: theme('colors.ctp.pink'),
							padding: '0.2rem 0.4rem',
							borderRadius: '0.25rem',
							fontWeight: '400',
						},
						'code::before': {
							content: '""',
						},
						'code::after': {
							content: '""',
						},
					},
				},
			}),
		},
	},
	plugins: [require('@tailwindcss/typography')],
};