/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				ctp: {
					rosewater: 'var(--ctp-rosewater)',
					flamingo: 'var(--ctp-flamingo)',
					pink: 'var(--ctp-pink)',
					mauve: 'var(--ctp-mauve)',
					red: 'var(--ctp-red)',
					maroon: 'var(--ctp-maroon)',
					peach: 'var(--ctp-peach)',
					yellow: 'var(--ctp-yellow)',
					green: 'var(--ctp-green)',
					teal: 'var(--ctp-teal)',
					sky: 'var(--ctp-sky)',
					sapphire: 'var(--ctp-sapphire)',
					blue: 'var(--ctp-blue)',
					lavender: 'var(--ctp-lavender)',
					text: 'var(--ctp-text)',
					subtext1: 'var(--ctp-subtext1)',
					subtext0: 'var(--ctp-subtext0)',
					overlay2: 'var(--ctp-overlay2)',
					overlay1: 'var(--ctp-overlay1)',
					overlay0: 'var(--ctp-overlay0)',
					surface2: 'var(--ctp-surface2)',
					surface1: 'var(--ctp-surface1)',
					surface0: 'var(--ctp-surface0)',
					base: 'var(--ctp-base)',
					mantle: 'var(--ctp-mantle)',
					crust: 'var(--ctp-crust)',
				},
			},
			fontFamily: {
				mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'Courier', 'monospace'],
			},
			typography: ({ theme }) => ({
				ctp: {
					css: {
						'--tw-prose-body': theme('colors.ctp.text'),
						'--tw-prose-headings': theme('colors.ctp.mauve'),
						'--tw-prose-lead': theme('colors.ctp.subtext1'),
						'--tw-prose-links': theme('colors.ctp.blue'),
						'--tw-prose-bold': theme('colors.ctp.lavender'),
						'--tw-prose-counters': theme('colors.ctp.rosewater'),
						'--tw-prose-bullets': theme('colors.ctp.rosewater'),
						'--tw-prose-hr': theme('colors.ctp.surface0'),
						'--tw-prose-quotes': theme('colors.ctp.subtext1'),
						'--tw-prose-quote-borders': theme('colors.ctp.surface2'),
						'--tw-prose-captions': theme('colors.ctp.subtext0'),
						'--tw-prose-code': theme('colors.ctp.pink'),
						'--tw-prose-pre-code': theme('colors.ctp.text'),
						'--tw-prose-pre-bg': theme('colors.ctp.mantle'),
						'--tw-prose-th-borders': theme('colors.ctp.surface1'),
						'--tw-prose-td-borders': theme('colors.ctp.surface0'),
						'--tw-prose-invert-body': theme('colors.ctp.text'),
						'--tw-prose-invert-headings': theme('colors.ctp.mauve'),
						'--tw-prose-invert-lead': theme('colors.ctp.subtext1'),
						'--tw-prose-invert-links': theme('colors.ctp.blue'),
						'--tw-prose-invert-bold': theme('colors.ctp.lavender'),
						'--tw-prose-invert-counters': theme('colors.ctp.rosewater'),
						'--tw-prose-invert-bullets': theme('colors.ctp.rosewater'),
						'--tw-prose-invert-hr': theme('colors.ctp.surface0'),
						'--tw-prose-invert-quotes': theme('colors.ctp.subtext1'),
						'--tw-prose-invert-quote-borders': theme('colors.ctp.surface2'),
						'--tw-prose-invert-captions': theme('colors.ctp.subtext0'),
						'--tw-prose-invert-code': theme('colors.ctp.pink'),
						'--tw-prose-invert-pre-code': theme('colors.ctp.text'),
						'--tw-prose-invert-pre-bg': theme('colors.ctp.mantle'),
						'--tw-prose-invert-th-borders': theme('colors.ctp.surface1'),
						'--tw-prose-invert-td-borders': theme('colors.ctp.surface0'),
						a: {
							color: theme('colors.ctp.blue'),
							textDecoration: 'none',
							'&:hover': {
								color: theme('colors.ctp.mauve'),
							},
						},
						code: {
							backgroundColor: theme('colors.ctp.surface0'),
							color: theme('colors.ctp.pink'),
							padding: '0.2rem 0.4rem',
							borderRadius: '0.25rem',
							fontWeight: '400',
						},
						'code::before': {
							content: '""',
						},
						'code::after': {
							content: '""',
						},
					},
				},
			}),
		},
	},
	plugins: [require('@tailwindcss/typography')],
};